name: Ubuntu Latest Lint and Test

on:
  push:
    branches: [master, development]
  pull_request:
    branches: [master, development]

jobs:
  lint:
    runs-on: ubuntu-latest

    timeout-minutes: 10

    strategy:
      matrix:
        node-version: [16.6.x]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn install --update-checksums
      - name: Run Linter
        run: yarn lint
      - name: Run Prettify Check
        run: yarn prettier --check .

  unit-test:
    runs-on: ubuntu-latest

    timeout-minutes: 10

    strategy:
      matrix:
        node-version: [16.6.x]
        mongodb-version: [4.4]

    services:
      mongodb:
        image: mongo
        ports:
          - 27017:27017

    env:
      ENV: testing
      MONGODB: mongodb://localhost:27017/megabot
      BOT_PREFIX: ++
      MOD_CHANNEL_ID: 123
      GUILD_ID: 321

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - run: yarn install --update-checksums

      - name: Install jest for testing
        run: yarn add --dev jest

      - run: yarn test --forceExit
